'use client';

import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { apiFetch } from '../../lib/api';
import { PolicySettings } from './policy-settings';
import { useUnsavedChanges } from '../../lib/unsaved-changes';
import { RuntimeFacts, RuntimeTable } from './runtime-panels';

const sections = [['overview', '运行总览'], ['jobs', '评估任务'], ['ai', 'AI 配置与健康'], ['storage', '存储与清理'], ['usage', '调用与费用'], ['settings', '设置与版本'], ['logs', '操作日志'], ['security', '安全事件'], ['sessions', '会话中心'], ['dependencies', '依赖状态']] as const;
const emptyFilters = { stage: '', status: '', scope: '', modelName: '', actionType: '', targetType: '', targetId: '', result: '', userId: '', videoId: '', from: '', to: '', page: 1 };
const usageColumns: Array<[string, string]> = [['isTrial', '试用数据'], ['collectionStatus', '采集状态'], ['stage', '阶段'], ['modelName', '模型'], ['status', '状态'], ['inputTokens', '输入用量'], ['outputTokens', '输出用量'], ['estimatedCost', '估算费用'], ['actualCost', '实际费用'], ['currency', '币种'], ['rateVersion', '费率版本']];
const jobsColumns: Array<[string, string]> = [['id', '任务编号'], ['isTrial', '试用数据'], ['waitingSeconds', '等待秒数'], ['processingSeconds', '处理秒数'], ['failureCategory', '错误分类'], ['stage', '阶段'], ['status', '状态'], ['attempts', '尝试次数'], ['createdAt', '创建时间']];
export function OperationsConsole() {
  const [section, setSection] = useState('overview'); const [data, setData] = useState<any>(null); const [extra, setExtra] = useState<any>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [revision, refresh] = useState(0);
  const [filters, setFilters] = useState(emptyFilters);
  const [detail, setDetail] = useState<any>(null); const [reason, setReason] = useState(''); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState(''); const [rates, setRates] = useState({ modelName: '', currency: 'CNY', inputPerMillion: '0', outputPerMillion: '0' });
  const baseVersionsRef = useRef<Record<string, number>>({ cost_rates: 0, business_notice: 0 });
  const [settingsReset, resetSettingsForms] = useState(0);
  const [baseVersions, setBaseVersions] = useState(baseVersionsRef.current);
  const dirtyKeys = useRef(new Set<string>()); const settingsLoaded = useRef(false); const [dirty, setDirty] = useState(false); const [historyPage, setHistoryPage] = useState(1);
  const serial = useRef(0); const detailSerial = useRef(0);
  useUnsavedChanges(dirty);
  function markDirty(key: string) { dirtyKeys.current.add(key); setDirty(true); }
  function savedKey(key: string) { dirtyKeys.current.delete(key); setDirty(dirtyKeys.current.size > 0); }
  function loadSettingBase(key: string, row: any) {
    const version = row?.version || 0;
    baseVersionsRef.current = { ...baseVersionsRef.current, [key]: version }; setBaseVersions(baseVersionsRef.current);
    if (key === 'cost_rates') { const r = row?.value; setRates(r ? { modelName: r.modelName, currency: r.currency, inputPerMillion: String(r.inputPerMillion), outputPerMillion: String(r.outputPerMillion) } : { modelName: '', currency: 'CNY', inputPerMillion: '0', outputPerMillion: '0' }); }
    if (key === 'business_notice') setNotice(row?.value.text || '');
  }
  function versionNotice(key: string) {
    const latest = data?.items?.find((row: any) => row.key === key);
    return <><p className="muted">草稿基准版本：{baseVersions[key]}</p>{(latest?.version || 0) > baseVersions[key] && <div role="alert"><p>服务端已有新版本 {latest.version}，当前草稿仍基于版本 {baseVersions[key]}。直接保存会产生版本冲突，请先查看历史或明确重载此项。</p><button className="secondary-button" type="button" disabled={busy} onClick={() => { if (window.confirm('重载将丢弃此项未保存编辑，确认加载最新版本？')) { loadSettingBase(key, latest); savedKey(key); } }}>重载此项最新版本</button></div>}</>;
  }
  const query = new URLSearchParams(Object.entries(filters).filter(([, v]) => v !== '').map(([k, v]) => [k, ['from', 'to'].includes(k) ? new Date(`${v}+08:00`).toISOString() : String(v)])).toString();
  useEffect(() => { const chosen = new URLSearchParams(window.location.search).get('section'); if (sections.some(([key]) => key === chosen)) setSection(chosen!); }, []);
  useEffect(() => {
    const controller = new AbortController(); const current = ++serial.current; detailSerial.current++; setLoading(true); if (section !== 'settings') setData(null); setExtra(null); setError(''); setDetail(null);
    const additional = section === 'usage' ? 'usage-summary' : section === 'settings' ? 'configuration-revisions' : section === 'jobs' ? 'job-statistics' : null;
    Promise.all([apiFetch<any>(`/api/admin/operations/${section}?${query}`, { signal: controller.signal }), additional ? apiFetch<any>(`/api/admin/operations/${additional}?${query}`, { signal: controller.signal }) : Promise.resolve(null)])
      .then(([primary, secondary]) => { if (current !== serial.current) return; setData(primary); setExtra(secondary); if (section === 'settings') setHistoryPage(1); if (section === 'settings') { for (const key of ['cost_rates', 'business_notice']) { const row = primary.items.find((v: any) => v.key === key); if (!settingsLoaded.current || (!dirtyKeys.current.has(key) && (row?.version || 0) >= baseVersionsRef.current[key])) loadSettingBase(key, row); } settingsLoaded.current = true; } })
      .catch(e => { if (!controller.signal.aborted) setError(e.message); }).finally(() => { if (current === serial.current) setLoading(false); });
    return () => { controller.abort(); };
  }, [section, query, revision]);
  function choose(value: string) { if (dirty && !window.confirm('配置尚未保存，确认离开并丢弃编辑？')) return; dirtyKeys.current.clear(); setDirty(false); settingsLoaded.current = false; setHistoryPage(1); serial.current++; detailSerial.current++; setData(null); setExtra(null); setDetail(null); setSection(value); setFilters(emptyFilters); setReason(''); setConfirmed(false); setMessage(''); history.replaceState(null, '', `${location.pathname}?section=${value}`); }
  async function action(path: string, body: unknown, method = 'POST') {
    setBusy(true); setError(''); setMessage('');
    try { const result = await apiFetch<any>(`/api/admin/operations/${path}`, { method, body: JSON.stringify(body) }); setMessage('操作已完成并记录日志。'); if (path.startsWith('settings/')) { const key = path.slice('settings/'.length); loadSettingBase(key, result); savedKey(key); } setReason(''); setConfirmed(false); refresh(n => n + 1); return result; }
    catch (e) { setError(e instanceof Error ? e.message : '操作失败'); return null; } finally { setBusy(false); }
  }
  async function changeHistory(page: number) { try { const history = await apiFetch<any>(`/api/admin/operations/configuration-revisions?page=${page}`); setExtra(history); setHistoryPage(page); } catch { setError('版本历史加载失败'); } }
  async function openJob(id: string) { const current = ++detailSerial.current; setError(''); try { const value = await apiFetch<any>(`/api/admin/operations/jobs/${id}`); if (current === detailSerial.current) { setDetail(value); setReason(''); setConfirmed(false); } } catch (e) { if (current === detailSerial.current) setError(e instanceof Error ? e.message : '加载失败'); } }
  const safetyForm = <><label>操作原因<input value={reason} onChange={e => setReason(e.target.value)} maxLength={500} required /></label><label className="checkbox-label"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />我已检查记录并确认本次操作{section === 'jobs' ? '，重试可能产生新费用，并使用原提交人的额度' : ''}</label></>;
  const canAct = confirmed && Boolean(reason.trim()) && !busy;
  return <main className="page" id="main-content"><div className="page-title"><div><p className="eyebrow">ADMIN CONSOLE</p><h1>管理运行中心</h1><p className="muted">任务与资源观察、费用采集及配置审计。时间统一按上海时区显示。</p></div><button className="secondary-button" onClick={() => { if (!dirty || window.confirm('刷新将丢弃未保存编辑，确认继续？')) { dirtyKeys.current.clear(); setDirty(false); settingsLoaded.current = false; resetSettingsForms(n => n + 1); refresh(n => n + 1); } }} disabled={loading || busy}>刷新</button></div>
    <nav className="runtime-tabs" aria-label="管理运行模块">{sections.map(([key, label]) => <button key={key} className={section === key ? 'primary-button' : 'secondary-button'} aria-current={section === key ? 'page' : undefined} onClick={() => choose(key)} disabled={busy}>{label}</button>)}</nav>
    {['overview', 'jobs', 'usage', 'logs', 'security', 'sessions'].includes(section) && <form key={section} className="runtime-filters" onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); setFilters({ scope: String(form.get('scope') || ''), modelName: String(form.get('modelName') || '').trim(), actionType: String(form.get('actionType') || '').trim(), targetType: String(form.get('targetType') || '').trim(), targetId: String(form.get('targetId') || '').trim(), result: String(form.get('result') || ''), stage: String(form.get('stage') || ''), status: String(form.get('status') || ''), userId: String(form.get('userId') || '').trim(), videoId: String(form.get('videoId') || '').trim(), from: String(form.get('from') || ''), to: String(form.get('to') || ''), page: 1 }); }}>
      {['jobs', 'usage'].includes(section) && <><label>阶段<select name="stage" defaultValue={filters.stage}><option value="">全部</option><option value="content">内容评估</option><option value="result">数据复盘</option><option value="final">最终建议</option></select></label><label>状态<select name="status" defaultValue={filters.status}><option value="">全部</option>{[['queued', '排队中'], ['running', '执行中'], ['retry_wait', '等待重试'], ['succeeded', '已完成'], ['failed', '失败'], ['needs_attention', '需人工处理'], ['uncertain', '结果未知']].map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><label>视频编号<input name="videoId" placeholder="视频 UUID" /></label></>}
      {['jobs', 'usage'].includes(section) && <label>数据范围<select name="scope" defaultValue={filters.scope}><option value="">全部（分类显示）</option><option value="formal">正式</option><option value="trial">试用</option></select></label>}{section === 'usage' && <label>模型名称<input name="modelName" /></label>}{['logs','security'].includes(section) && <><label>操作类型<input name="actionType" /></label><label>目标类型<input name="targetType" /></label><label>目标编号<input name="targetId" /></label><label>结果<select name="result"><option value="">全部</option><option value="success">成功</option><option value="failure">失败</option><option value="denied">拒绝</option></select></label></>}
      {section !== "overview" && <label>用户编号<input name="userId" placeholder="用户 UUID" /></label>}<label>起始时间<input name="from" type="datetime-local" /></label><label>结束时间<input name="to" type="datetime-local" /></label><button className="secondary-button" type="submit">筛选</button>
    </form>}
    {error && <p className="error-message" role="alert">{error}</p>}{message && <p role="status">{message}</p>}{loading && <p role="status">正在加载运行数据…</p>}
    {data && <section className="card runtime-panel">
      {section === 'overview' && <><RuntimeFacts values={{ 活跃账号: data.activeUsers, 正式视频: data.formalVideos, 试用视频: data.trialVideos, 任务执行进程: data.worker, 观察时间: data.observedAt }} /><h2>日期内任务</h2><RuntimeTable rows={data.jobs} columns={[["stage","阶段"],["isTrial","试用数据"],["status","状态"],["count","任务数"]]} /><h2>当前积压与风险（不受日期范围影响）</h2><RuntimeFacts values={{ 有效访客: data.visitorAccounts, 超时排队: data.overdueQueue, 站点: data.site?.name, 公告: data.site?.notice }} /><RuntimeTable rows={data.currentBacklog || data.jobs} columns={[["stage", "阶段"], ["isTrial", "试用数据"], ["status", "状态"], ["count", "任务数"]]} action={row => <button className="secondary-button" onClick={() => { choose("jobs"); setFilters({ ...emptyFilters, stage: row.stage, status: row.status, scope: row.isTrial ? "trial" : "formal" }); }}>查看对应任务</button>} /><h3>近期到期账号</h3><RuntimeTable rows={data.expiringAccounts || []} columns={[["name","账号"],["expiresAt","到期时间"]]} action={row => <Link href={`/admin/users/${row.id}`}>查看账号</Link>} /><div className="button-row"><button className="secondary-button" onClick={() => choose('jobs')}>进入任务筛选</button><Link href="/admin/users">账号管理</Link><Link href="/admin/roles">角色权限</Link></div></>}
      {section === 'jobs' && <><h2>等待与处理耗时</h2><p>秒数口径；处理时长含重试间隔；成功率分母仅含终态任务，未知不按零处理。</p><RuntimeTable rows={extra?.groups || []} columns={[["stage","阶段"],["isTrial","试用数据"],["successRate","成功率"],["waitingP50","等待 P50"],["waitingP95","等待 P95"],["processingP50","处理 P50"],["processingP95","处理 P95"]]} /><RuntimeTable rows={data.items} columns={jobsColumns} action={row => <button className="secondary-button" onClick={() => openJob(row.id)}>查看尝试记录</button>} />{detail && <section className="runtime-panel"><h2>任务详情</h2><RuntimeFacts values={{ 任务编号: detail.id, 视频编号: detail.videoId, 提交人: detail.actorId, 状态: detail.status, 原任务: detail.retriedFromId }} /><Link href={`/videos/${detail.videoId}`}>打开视频</Link><h3>历次执行</h3><RuntimeTable rows={detail.attemptsHistory} columns={[["attemptNumber", "次数"], ["status", "状态"], ["failureCategory", "错误分类"], ["processingSeconds", "处理秒数"], ["startedAt", "开始时间"], ["externalStartedAt", "外部请求开始"], ["completedAt", "完成时间"]]} /><h3>调用记录</h3><RuntimeTable rows={detail.usage} columns={usageColumns} />{['failed', 'needs_attention'].includes(detail.status) && <form onSubmit={async e => { e.preventDefault(); await action(`jobs/${detail.id}/retry`, { reason, confirmed }); }}><p>重试会保留原记录并建立新评估。原任务状态、最新输入、身份和额度均由后端再次校验。</p>{safetyForm}<button className="primary-button" disabled={!canAct}>确认重试</button></form>}</section>}</>}
      {section === 'ai' && <><RuntimeFacts values={{ 凭据已配置: data.configured, 连通性: data.connection, 付费诊断: data.paidDiagnostic }} /><h2>已保存模型配置</h2><RuntimeTable rows={data.configs} columns={[["agentType", "评估用途"], ["provider", "服务商"], ["modelName", "模型"], ["enabled", "启用"], ["maxTokens", "输出上限"], ["updatedAt", "更新时间"]]} /><h3>无启用配置时的默认模型</h3><RuntimeTable rows={data.effectiveFallbacks} columns={[["stage", "阶段"], ["modelName", "模型"]]} /><h3>最近 24 小时调用</h3><RuntimeTable rows={data.callsLast24h} columns={[["stage", "阶段"], ["isTrial", "试用数据"], ["status", "状态"], ["failureCategory", "错误分类"], ["collectionStatus", "采集状态"], ["latestCompletedAt", "最近完成时间"], ["count", "次数"]]} /></>}
      {section === 'storage' && <><RuntimeFacts values={{ 应用登记文件数: data.applicationFiles, 应用登记字节数: data.applicationBytes, COS配置: data.cos.configured, COS远端清单: data.cos.remoteInventory, OSS配置: data.oss.configured, OSS远端清单: data.oss.remoteInventory, 历史清理覆盖: data.oss.historicalCleanupCoverage, 云账单: data.cloudBilling, 直传过期待清理: data.directUploadCleanup.overdue, 直传清理失败: data.directUploadCleanup.failed, 直传已清理: data.directUploadCleanup.cleaned, 临时文件待保留复核: data.retentionReview?.temporaryObjects, 审计记录待保留复核: data.retentionReview?.auditRecords }} /><p className="muted">应用登记容量不等于云存储实际容量；临时文件状态仅覆盖采集启用后的处理。OSS 清理失败需人工检查云端。</p><RuntimeTable rows={data.temporaryObjects} columns={[["provider", "存储服务"], ["status", "状态"], ["count", "记录数"]]} /></>}
      {section === 'usage' && <><RuntimeFacts values={{ 采集范围: data.coverage, 云账单: extra?.billingStatus }} /><p>估算按调用开始时保存的人工费率计算，实际账单尚未接入。未知用量或费用留空，不按零费用统计。</p><h2>分类汇总</h2><RuntimeTable rows={extra?.groups || []} columns={[["isTrial", "试用数据"], ["collectionStatus", "采集状态"], ["failureCategory", "错误分类"], ["stage", "阶段"], ["modelName", "模型"], ["status", "状态"], ["calls", "调用数"], ["estimatedCost", "已知估算合计"], ["estimateObserved", "有估算的调用数"], ["actualCost", "已知实际合计"], ["actualObserved", "有实际费用的调用数"], ["currency", "币种"]]} /><h2>调用明细</h2><RuntimeTable rows={data.items} columns={[["createdAt", "时间"], ["jobId", "任务编号"], ...usageColumns]} /><form onSubmit={async e => { e.preventDefault(); const result = await action(`usage/export?${query}`, { reason, confirmed }); if (result) { const blob = URL.createObjectURL(new Blob(['\uFEFF', result.csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = blob; link.download = result.filename; link.click(); setTimeout(() => URL.revokeObjectURL(blob), 1000); } }}><h3>导出当前筛选结果</h3><p>最多 1000 条调用，导出会记录操作日志。导出使用已应用筛选（修改输入后请先点筛选）。</p><RuntimeFacts values={{ 阶段: filters.stage || '全部', 范围: filters.scope || '全部', 用户: filters.userId || '全部', 模型: filters.modelName || '全部', 起始: filters.from || '不限', 结束: filters.to || '不限' }} />{safetyForm}<button className="secondary-button" disabled={!canAct}>确认导出 CSV</button></form></>}
      {section === 'settings' && <><p><Link href="/settings/benchmarks">编辑业务基准</Link> · 基准变更自动追加历史版本；已排队评估继续使用原快照。</p><form onSubmit={async e => { e.preventDefault(); await action('settings/cost_rates', { value: { provider: 'aliyun_bailian', modelName: rates.modelName, currency: rates.currency, inputPerMillion: Number(rates.inputPerMillion), outputPerMillion: Number(rates.outputPerMillion) }, expectedVersion: baseVersions.cost_rates, reason, confirmed }, 'PUT'); }}><h2>费用估算费率</h2>{versionNotice('cost_rates')}<p>仅作用于之后发起且模型名称相同的调用；请按已核实的计价单位填写。</p><label>模型名称<input disabled={busy} value={rates.modelName} onChange={e => { markDirty('cost_rates'); setRates({ ...rates, modelName: e.target.value }); }} required pattern="[a-zA-Z0-9._-]{1,100}" /></label><label>币种<select disabled={busy} value={rates.currency} onChange={e => { markDirty('cost_rates'); setRates({ ...rates, currency: e.target.value }); }}><option>CNY</option><option>USD</option></select></label><label>每百万输入 Token 费用<input type="number" min="0" max="100000" step="any" required disabled={busy} value={rates.inputPerMillion} onChange={e => { markDirty('cost_rates'); setRates({ ...rates, inputPerMillion: e.target.value }); }} /></label><label>每百万输出 Token 费用<input type="number" min="0" max="100000" step="any" required disabled={busy} value={rates.outputPerMillion} onChange={e => { markDirty('cost_rates'); setRates({ ...rates, outputPerMillion: e.target.value }); }} /></label>{safetyForm}<button className="primary-button" disabled={!canAct}>保存费率版本</button></form><form onSubmit={async e => { e.preventDefault(); await action('settings/business_notice', { value: { text: notice }, expectedVersion: baseVersions.business_notice, reason, confirmed }, 'PUT'); }}><h2>管理业务备注</h2>{versionNotice('business_notice')}<label>备注<input disabled={busy} value={notice} onChange={e => { markDirty('business_notice'); setNotice(e.target.value); }} maxLength={300} /></label><p className="muted">使用上方填写的操作原因与确认状态。</p><button className="secondary-button" disabled={!canAct}>保存备注</button></form><PolicySettings key={settingsReset} data={data} onReset={savedKey} onDirty={markDirty} onSaved={key => { savedKey(key); refresh(n => n + 1); }} /><h2>配置审计与基准版本</h2><RuntimeTable rows={extra?.items || []} columns={[["kind", "类别"], ["targetId", "配置编号"], ["version", "版本"], ["actorId", "操作人"], ["reason", "原因"], ["createdAt", "时间"]]} action={row => <details><summary>查看此版本</summary><RuntimeFacts values={row.value || {}} /></details>} />{extra && <div className="pagination"><button disabled={historyPage === 1} onClick={() => changeHistory(historyPage - 1)}>上一页</button><span>第 {historyPage} 页，共 {extra.total} 条</span><button disabled={historyPage * extra.pageSize >= extra.total} onClick={() => changeHistory(historyPage + 1)}>下一页</button></div>}</>}
      {['logs', 'security'].includes(section) && <><RuntimeTable rows={data.items} columns={[["createdAt", "时间"], ["actionType", "操作"], ["userId", "操作人"], ["targetType", "目标类型"], ["targetId", "目标编号"], ["result", "结果"]]} /><form onSubmit={async e => { e.preventDefault(); const result = await action(`${section}/export?${query}`, { reason, confirmed }); if (result) { const blob = URL.createObjectURL(new Blob(["\uFEFF", result.csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = blob; link.download = result.filename; link.click(); setTimeout(() => URL.revokeObjectURL(blob), 1000); } }}><h3>导出已应用筛选的脱敏日志</h3><p>不含内部请求、响应、错误栈或安全凭据，最多1000条。</p>{safetyForm}<button disabled={!canAct}>确认导出日志</button></form></>}
      {section === 'sessions' && <RuntimeTable rows={data.items} columns={[["userId", "用户编号"], ["createdAt", "创建时间"], ["expiresAt", "到期时间"], ["revokedAt", "撤销时间"], ["active", "当前有效"]]} action={row => <Link href={`/admin/users/${row.userId}`}>管理账号会话</Link>} />}
      {section === 'dependencies' && <><RuntimeFacts values={{ 应用版本: data.applicationVersion, 部署时间: data.deployedAt, API进程: data.api, 数据库: data.database, 执行进程心跳: data.worker.status, 最近心跳: data.worker.lastSeenAt, AI服务: data.ai, 文件存储: data.storage, 服务器资源: data.resources, 备份: data.backups, 证书: data.certificates, 云账单: data.cloudBilling, 付费诊断: data.paidDiagnostic }} /><p>存活检查只确认 API 进程；就绪检查确认数据库可连接。外部依赖未经诊断时不会显示为正常，也不会自动触发付费请求。</p></>}
      {data.total !== undefined && <div className="pagination"><button disabled={filters.page === 1 || loading} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}>上一页</button><span>第 {filters.page} 页，共 {data.total} 条</span><button disabled={filters.page * data.pageSize >= data.total || loading} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>下一页</button></div>}
    </section>}
  </main>;
}
