'use client';

import Link from 'next/link';
import { FormEvent, use, useCallback, useEffect, useState } from 'react';
import { QuotaAdjustmentForm, QuotaItem } from '@/components/admin/quota-adjustment-form';
import { apiFetch } from '@/lib/api';
import { ManagedUser, roleLabels } from '@/lib/admin-types';

type Session = { id: string; createdAt: string; expiresAt: string; revokedAt: string | null; ipAddress?: string | null; userAgent?: string | null };
const formatTime = (value?: string | null) => value ? new Intl.DateTimeFormat('zh-CN', { timeZone: 'Asia/Shanghai', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';

export default function AdminUserDetailPage({ params: pendingParams }: { params: Promise<{ id: string }> }) {
  const params = use(pendingParams);
  const [user, setUser] = useState<ManagedUser | null>(null), [sessions, setSessions] = useState<Session[]>([]), [quotas, setQuotas] = useState<QuotaItem[]>([]);
  const [error, setError] = useState(''), [notice, setNotice] = useState(''), [credential, setCredential] = useState('');
  const load = useCallback(async () => { setError(''); try { const [detail, sessionData, quotaData] = await Promise.all([apiFetch<{ user: ManagedUser }>(`/api/admin/users/${params.id}`), apiFetch<{ items: Session[] }>(`/api/admin/users/${params.id}/sessions`), apiFetch<{ quotas: QuotaItem[] }>(`/api/admin/users/${params.id}/quotas`)]); setUser(detail.user); setSessions(sessionData.items); setQuotas(quotaData.quotas); } catch (err) { setError(err instanceof Error ? err.message : '账号详情加载失败。'); } }, [params.id]);
  useEffect(() => { void load(); }, [load]);
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setError(''); try { const result = await apiFetch<{ user: ManagedUser }>(`/api/admin/users/${params.id}`, { method: 'PATCH', body: JSON.stringify({ name: data.get('name'), role: data.get('role'), status: data.get('status'), expiresAt: data.get('expiresAt') ? new Date(String(data.get('expiresAt'))).toISOString() : null, reason: data.get('reason') }) }); setUser(result.user); setNotice('账号资料已更新，相关旧会话会按安全规则失效。'); } catch (err) { setError(err instanceof Error ? err.message : '更新失败。'); } }
  async function action(path: string, reason: string, confirmText?: string) { if (!reason.trim()) return setError('请先填写操作原因。'); if (confirmText && !window.confirm(confirmText)) return; setError(''); try { const result = await apiFetch<{ initialPassword?: string }>(`/api/admin/users/${params.id}/${path}`, { method: 'POST', body: JSON.stringify({ reason }) }); if (result.initialPassword) setCredential(result.initialPassword); setNotice('操作已完成。'); await load(); } catch (err) { setError(err instanceof Error ? err.message : '操作失败。'); } }
  if (error && !user) return <main className="page" id="main-content"><div className="error-state" role="alert"><p>{error}</p><button className="button secondary" onClick={() => void load()}>重试</button></div></main>;
  if (!user) return <main className="page" id="main-content"><p className="muted" role="status">正在加载账号详情…</p></main>;
  return <main className="page" id="main-content"><Link className="text-link" href="/admin/users">← 返回账号列表</Link><div className="page-title section-gap"><div><p className="eyebrow">ACCOUNT</p><h1>{user.name}</h1><p className="muted">{user.account} · {roleLabels[user.role] || user.role}</p></div></div>{error ? <p className="error" role="alert">{error}</p> : null}{notice ? <p className="success" role="status">{notice}</p> : null}{credential ? <div className="credential-notice" role="status"><strong>新初始密码只显示一次</strong><code>{credential}</code><button className="button secondary" onClick={() => setCredential('')}>我已保存，关闭提示</button></div> : null}<div className="detail-grid"><section className="panel"><h2>账号资料</h2><form className="form-grid" onSubmit={update}><div className="form-field"><label htmlFor="detail-name">姓名</label><input id="detail-name" name="name" defaultValue={user.name} required /></div><div className="form-field"><label htmlFor="detail-role">角色</label><select id="detail-role" name="role" defaultValue={user.role}>{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="form-field"><label htmlFor="detail-status">状态</label><select id="detail-status" name="status" defaultValue={user.status}><option value="active">启用</option><option value="disabled">停用</option><option value="archived">已归档</option></select></div><div className="form-field"><label htmlFor="detail-expiry">到期时间</label><input id="detail-expiry" name="expiresAt" type="datetime-local" defaultValue={user.expiresAt ? new Date(user.expiresAt).toISOString().slice(0, 16) : ''} /></div><div className="form-field full"><label htmlFor="update-reason">变更原因</label><input id="update-reason" name="reason" required /></div><div className="full"><button className="button">保存账号资料</button></div></form></section><SensitiveActions onAction={action} /></div><div className="section-gap"><QuotaAdjustmentForm userId={params.id} quotas={quotas} onAdjusted={load} /></div><section className="panel section-gap"><h2>登录会话</h2>{sessions.length === 0 ? <p className="empty-state">暂无会话记录。</p> : <div className="table-scroll" tabIndex={0}><table><thead><tr><th>创建时间</th><th>到期时间</th><th>IP</th><th>状态</th><th>设备</th></tr></thead><tbody>{sessions.map((session) => <tr key={session.id}><td>{formatTime(session.createdAt)}</td><td>{formatTime(session.expiresAt)}</td><td>{session.ipAddress || '—'}</td><td>{session.revokedAt ? `已撤销 ${formatTime(session.revokedAt)}` : '有效'}</td><td>{session.userAgent || '—'}</td></tr>)}</tbody></table></div>}</section></main>;
}

function SensitiveActions({ onAction }: { onAction: (path: string, reason: string, confirmText?: string) => Promise<void> }) {
  const [reason, setReason] = useState('');
  return <section className="panel"><h2>安全操作</h2><div className="form-field"><label htmlFor="security-reason">操作原因</label><input id="security-reason" value={reason} onChange={(event) => setReason(event.target.value)} /></div><div className="button-stack"><button className="button secondary" type="button" onClick={() => void onAction('reset-password', reason, '确认重置该账号密码并使现有会话失效？')}>重置密码</button><button className="button secondary" type="button" onClick={() => void onAction('revoke-sessions', reason, '确认撤销该账号全部会话？')}>撤销全部会话</button><button className="button danger-button" type="button" onClick={() => void onAction('archive', reason, '归档后不能恢复，确认继续？')}>归档账号</button></div></section>;
}
