export const OperationLogAction = {
  LoginSuccess: 'login_success',
  LoginFailed: 'login_failed',
  PermissionDenied: 'permission_denied',
  VideoUploaded: 'video_uploaded',
  VideoDetailViewed: 'video_detail_viewed',
  VideoFileAccessed: 'video_file_accessed',
  AiContentReviewStarted: 'ai_content_review_started',
  AiContentReviewRecovered: 'ai_content_review_recovered',
  AiContentReviewCompleted: 'ai_content_review_completed',
  AiContentReviewFailed: 'ai_content_review_failed',
  AiContentReviewViewed: 'ai_content_review_viewed',
  SupervisorReviewApproved: 'supervisor_review_approved',
  SupervisorReviewRevisionRequired: 'supervisor_review_revision_required',
  SupervisorReviewInvalidContent: 'supervisor_review_invalid_content',
  SupervisorReviewViewed: 'supervisor_review_viewed',
  VideoRevisionUploaded: 'video_revision_uploaded',
  ResultMetricSnapshotCreated: 'result_metric_snapshot_created',
  AiResultReviewStarted: 'ai_result_review_started',
  AiResultReviewRecovered: 'ai_result_review_recovered',
  AiResultReviewCompleted: 'ai_result_review_completed',
  AiResultReviewFailed: 'ai_result_review_failed',
  RuleEngineExecuted: 'rule_engine_executed',
  FinalEvaluationStarted: 'final_evaluation_started',
  FinalEvaluationRecovered: 'final_evaluation_recovered',
  FinalEvaluationCompleted: 'final_evaluation_completed',
  FinalEvaluationFailed: 'final_evaluation_failed',
  FinalEvaluationConfirmed: 'final_evaluation_confirmed',
  FinalGradeAdjusted: 'final_grade_adjusted',
  ExcellentCaseMarked: 'excellent_case_marked',
  NegativeCaseMarked: 'negative_case_marked',
  CaseMarkRemoved: 'case_mark_removed',
} as const;

export type OperationLogAction = (typeof OperationLogAction)[keyof typeof OperationLogAction];
